[build]
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://andy1388.github.io"}
  methods = ["POST", "OPTIONS"]

[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://andy1388.github.io"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Max-Age = "86400" 