[build]
  functions = "functions"
  publish = "."

[dev]
  functions = "functions"
  publish = "."

# 首先處理 CORS 預檢請求
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Content-Type", Access-Control-Allow-Methods = "POST, OPTIONS"}
  methods = ["OPTIONS"]

# 然後處理 API 請求
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# 最後是通用的 CORS 配置
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS" 