[build]
  functions = "functions"
  publish = "."

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Max-Age = "86400" 