[build]
  functions = "functions"
  publish = "."

[dev]
  functions = "functions"
  publish = "." 

[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Accept, Origin, X-Requested-With"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Max-Age = "86400" 