[build]
  functions = "functions"
  publish = "."

[dev]
  functions = "functions"
  publish = "." 

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://andy1388.github.io"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS" 